learning_templates/basic_app/urls.py
from django.urls import path
from . import views

# Template tagging
app_name = "basic_app"

urlpatterns = [
    path("relative/", views.relative, name="relative"),
    path("other/", views.other, name="other"),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("basic_app/",include("basic_app.urls")),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {"text":"hello world","number":100}
    return render(request,"basic_app/index.html",context=context_dict)

def other(request):
    return render(request,"basic_app/other.html")

def relative(request):
    return render(request,"basic_app/relative_url_templates.html")

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="navbar-brand"><a href="{% url "index" %}">BRAND</a></li>
                <li class="nav-link"><a href="{% url "admin:index" %}">Admin</a></li>
                <li class="nav-link"><a href="{% url "basic_app:other" %}">Other</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">

        {% block body_block %}
        


        {% endblock %}
    </div>

</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
    {% block body_block %}
        <h1>Welcome to Homepage</h1>
        <h2>This is index.html page showing!</h2>
        <h3>{{ text|bla:"world" }}</h3>
        <h3>{{ number|add:"99" }}</h3>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
        <h1>Welcome to other</h1>
        <h2>This is an example of template inheritance!</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Relative url templates</title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url "basic_app:other" %}">The Other Page</a>
    <a href="{% url "admin:index" %}">LINK TO ADMIN</a>
    <a href="{% url "index" %}">Link to INdex</a>
</body>
</html>